name: user_repository
description: "user_repository"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^4.15.8
  equatable: ^2.0.5
  file_picker: ^8.0.0+1
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  image_picker: ^1.0.8
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  path: ^1.8.3
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  go_router: ^14.2.3
  animations: ^2.0.11
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.17
  build_runner: ^2.1.10
  json_serializable: ^6.6.1
  flutter_gen_runner:


flutter:
  uses-material-design: true

