name: WeChat
description: "Telegram killer"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^4.15.8
  equatable: ^2.0.5
  file_picker: ^8.0.0+1
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  image_picker: ^1.0.8
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  path: ^1.8.3
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  go_router: ^14.2.3
  animations: ^2.0.11
  page_transition: ^2.1.0
  firebase_storage_web:
  flutter_card_swiper: ^7.0.1
  user_repository:
    path: packages/user_repository
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.17
  build_runner: ^2.1.10
  json_serializable: ^6.6.1
  flutter_gen_runner:
  flutter_svg:


flutter:
  uses-material-design: true
  assets:
    - assets/images/splash/
    - assets/images/icons/
    - assets/images/help/
    - assets/vectors/navigator_icons/
    - assets/lottie/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-Regular.otf
          weight: 300
        - asset: assets/fonts/Inter-Thin.otf
          weight: 100
