name: splash
description: "Splash_screen"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  navigation:
    path: ../../../navigation
  core_ui: 
    path: ../../../core_ui
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.12
  flutter_gen: ^5.7.0
  flutter_gen_runner: ^5.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/